# Generated by Django 4.1 on 2023-03-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='photo',
            field=models.ImageField(null=True, upload_to='page'),
        ),
    ]
