# Generated by Django 4.1 on 2023-03-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_carousel_rename_photo_page_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayınlandı'), ('deleted', 'Silindi')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
