# Generated by Django 4.1 on 2023-03-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('man', 'Erkek'), ('woman', 'Kadın'), ('unisex', 'Unisex')], default='unisex', max_length=6),
        ),
        migrations.AddField(
            model_name='category',
            name='is_men',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_women',
            field=models.BooleanField(default=False),
        ),
    ]
